# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("byro_fints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fintsaccount",
            name="last_fetch_date",
            field=models.DateField(null=True),
        ),
    ]
