# Generated by Django 2.1 on 2018-08-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("byro_fints", "0004_auto_20180828_2153"),
    ]

    operations = [
        migrations.AddField(
            model_name="fintsaccount",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Display name"
            ),
        ),
    ]
