# Generated by Django 2.1 on 2018-10-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("byro_fints", "0005_fintsaccount_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="fintsaccount",
            name="caps",
            field=models.BigIntegerField(default=0),
        ),
    ]
