# Generated by Django 3.2.10 on 2022-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("byro_fints", "0007_auto_20190814_1614"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fintsuserlogin",
            name="available_tan_media",
            field=models.JSONField(default=list),
        ),
    ]
