# Generated by Django 3.2.13 on 2022-04-16 15:53

import byro_fints.models
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('byro_fints', '0008_alter_fintsuserlogin_available_tan_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='fintsuserlogin',
            name='state',
            field=enumfields.fields.EnumField(default='active', enum=byro_fints.models.FinTSUserLoginState, max_length=10),
            preserve_default=False,
        ),
    ]
